spring:
  application:
    name:
      config-service
  cloud:
    config:
      server:
        git:
          uri:
            https://github.com/Amyn617/ecommerce-distributed-system/config-repo

server:
  port:
    9999
